# Generated by Django 3.0 on 2021-02-28 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('Title_of_the_audiobook', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Duration_in_sec', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('Name_of_the_Podcast', models.CharField(max_length=100)),
                ('Duration_in_sec', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('Name_of_the_song', models.CharField(max_length=100)),
                ('Duration_in_sec', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
